# This file was generated by GoReleaser. DO NOT EDIT.
cask "tfdsprune" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "ece1c0b55ba08c598854b0d3d5a465174ea349c1cbcabf988ab65fe56dcc7041"
      url "https://github.com/winebarrel/tfdsprune/releases/download/v#{version}/tfdsprune_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "58ca21b1baddb8e5eacc086748121f540dd15d18512125ff7076c57813c6ac72"
      url "https://github.com/winebarrel/tfdsprune/releases/download/v#{version}/tfdsprune_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "419af2ce752b42f65f5370857684f3afa69c6a461b1becb0b10fdb1f87415e21"
      url "https://github.com/winebarrel/tfdsprune/releases/download/v#{version}/tfdsprune_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d36970afd3d4d10e2e9c8cb8b33f95ea7b29e578a5375bebe1445a2666fb9aa0"
      url "https://github.com/winebarrel/tfdsprune/releases/download/v#{version}/tfdsprune_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tfdsprune"
  desc "tfdsprune is a tool to remove unused Terraform data source definitions."
  homepage "https://github.com/winebarrel/tfdsprune"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tfdsprune"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tfdsprune"]
    end
  end

  # No zap stanza required

end
